volumes:
  pg_passenger:
  pg_driver:
  pg_rating:
  pg_ride:
  pg_keycloak:
  kafka_data:
  zookeeper_data:
  elastic_data:

services:

  discovery-service:
    image: discovery-service
    container_name: discovery-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: discovery-service
    ports:
      - "8761:8761"
    environment:
      - ZIPKIN=${ZIPKIN}
    networks:
      - cab-aggregator-app
    depends_on:
      ride_db:
        condition: service_healthy
      passenger_db:
        condition: service_healthy
      driver_db:
        condition: service_healthy
      rating_db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      zipkin:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://discovery-service:8761/actuator/health" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s

  config-server:
    image: config-server
    container_name: config-server
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: config-server
    expose:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - ZIPKIN=${ZIPKIN}
    depends_on:
      discovery-service:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://discovery-service:8761/eureka/apps/config-server || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 25s

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: auth-service
    expose:
      - "8085:8085"
    environment:
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KEYCLOAK_ADMIN_CLIENT_URL=${KEYCLOAK_ADMIN_CLIENT_URL}
      - CLIENT_ID_FOR_AUTH_KC=${CLIENT_ID_FOR_AUTH_KC}
      - KC_REALM=${KC_REALM}
      - EUREKA_URL=${EUREKA_URL}
    depends_on:
      driver-service:
        condition: service_healthy
      passenger-service:
        condition: service_healthy
      rating-service:
        condition: service_healthy
      ride-service:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://auth-service:8085/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  driver-service:
    image: driver-service:latest
    container_name: driver-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: driver-service
    expose:
      - "8082:8082"
    environment:
      - DB_URL=${DRIVER_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - KAFKA=${KAFKA}
      - ZIPKIN=${ZIPKIN}
      - JWT_ISSUER_URL=${JWT_ISSUER_URL}
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://driver-service:8082/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 90s

  passenger-service:
    image: passenger-service:latest
    container_name: passenger-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: passenger-service
    expose:
      - "8081:8081"
    environment:
      - DB_URL=${PASSENGER_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - KAFKA=${KAFKA}
      - ZIPKIN=${ZIPKIN}
      - JWT_ISSUER_URL=${JWT_ISSUER_URL}
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://passenger-service:8081/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 90s

  rating-service:
    image: rating-service:latest
    container_name: rating-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: rating-service
    expose:
      - "8084:8084"
    environment:
      - DB_URL=${RATING_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - KAFKA=${KAFKA}
      - ZIPKIN=${ZIPKIN}
      - JWT_ISSUER_URL=${JWT_ISSUER_URL}
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://rating-service:8084/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 90s

  ride-service:
    image: ride-service:latest
    container_name: ride-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: ride-service
    expose:
      - "8083:8083"
    environment:
      - DB_URL=${RIDE_DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - ZIPKIN=${ZIPKIN}
      - JWT_ISSUER_URL=${JWT_ISSUER_URL}
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://ride-service:8083/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 90s

  gateway-service:
    image: gateway-service:latest
    container_name: gateway-service
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        SERVICE_NAME: gateway-service
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_URL}
      - ZIPKIN=${ZIPKIN}
    depends_on:
      driver-service:
        condition: service_healthy
      passenger-service:
        condition: service_healthy
      rating-service:
        condition: service_healthy
      ride-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://gateway-service:8888/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 90s

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/wurstmeister/zookeeper
    networks:
      - cab-aggregator-app
    depends_on:
      kibana:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "29092:29092"
      - "9092:9092"
    volumes:
      - kafka_data:/wurstmeister/kafka
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "nc -z kafka 29092" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  passenger_db:
    image: postgres:15.1-alpine
    container_name: passenger-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=passenger_db
    volumes:
      - pg_passenger:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - cab-aggregator-app
    depends_on:
      kibana:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d passenger_db" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s

  driver_db:
    image: postgres:15.1-alpine
    container_name: driver-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=driver_db
    volumes:
      - pg_driver:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cab-aggregator-app
    depends_on:
      kibana:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d driver_db" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s

  ride_db:
    image: postgres:15.1-alpine
    container_name: ride-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=ride_db
    volumes:
      - pg_ride:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      kibana:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d ride_db" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s

  rating_db:
    image: postgres:15.1-alpine
    container_name: rating-db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=rating_db
    volumes:
      - pg_rating:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    depends_on:
      kibana:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d rating_db" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s

  keycloak_db:
    image: postgres:15.1-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_keycloak:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    depends_on:
      kibana:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d keycloak_db" ]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: [ "start-dev", "--http-port=7000", "--import-realm", "--health-enabled=true" ]
    environment:
      KC_DB: postgres
      KC_DB_URL: ${KEYCLOAK_DB_URL}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak/realms:/opt/keycloak/data/import
    ports:
      - "7000:7000"
    depends_on:
      keycloak_db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "exec 3<>/dev/tcp/localhost/7000 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 45s
    networks:
      - cab-aggregator-app

  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 5s
      retries: 5
      timeout: 15s
      start_period: 30s
    networks:
      - cab-aggregator-app

  logstash:
    image: logstash:7.14.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - ./monitoring/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9600/_node/stats" ]
      interval: 5s
      retries: 5
      timeout: 15s
      start_period: 30s
    networks:
      - cab-aggregator-app

  filebeat:
    image: elastic/filebeat:7.14.0
    container_name: filebeat
    command: ["filebeat", "-e", "--strict.perms=false"]
    user: root
    volumes:
      - ./monitoring/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      logstash:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pgrep filebeat || exit 1"]
      interval: 5s
      retries: 5
      timeout: 15s
      start_period: 30s
    networks:
      - cab-aggregator-app

  kibana:
    image: kibana:7.14.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
    depends_on:
      filebeat:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/status"]
      interval: 5s
      retries: 5
      timeout: 15s
      start_period: 30s
    networks:
      - cab-aggregator-app

  grafana:
    container_name: grafana
    build: './monitoring/grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/-/healthy" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 25s

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus:/prometheus
    depends_on:
      gateway-service:
        condition: service_healthy
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 25s

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - cab-aggregator-app
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:9411/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  cab-aggregator-app:
    driver: bridge
